### ISSUE TITLE
Add local development guide

### ISSUE THREAD

**Issue by jaredpalmer** [styfle/og-image#46]
Seems like there is some creative proxying happening? It would be great to add a CONTRIBUTING.md or at local development guide for running both the app and image service at the same time

**Comment by styfle** [comment]
Hi Jared,

Yeah, I totally agree!

The Now 2.0 platform handles [routing](https://github.com/styfle/og-image/blob/master/now.json#L12) at deployment time so there will soon be a now-dev feature to get this routing locally. But it's not available yet 😢 

The short answer is something like

1. Run `npm run watch` to get TS to JS compilation going 
2. Run the backend with `npm start` and visit http://localhost:13463/Boom.png
3. Run the frontend with `npx http-server .` and visit http://localhost:8080/public/index.html
4. One **minor** change is that `index.html` has as script that should be `../dist/browser.js` instead of `browser.js` (this is due to the routes I mentioned above)

Sorry about the inconvenience, now dev will be ready in a month or so 😞 
Does that get you going in the right direction? 😄

**Comment by arteagabriel** [comment]
This project is super cool! I was able to get the local environment working for the most part following these instructions, however the preview browser is running into an error locally. If I deploy to Now the preview browser works just fine after reverting the changes to index.html/browser.ts. Any suggestions?

**Comment by styfle** [comment]
@arteagabriel What does the error say?

I added one additional change to [contributing.md](https://github.com/styfle/og-image/blob/master/CONTRIBUTING.md) regarding the URL on [line 190](https://github.com/styfle/og-image/blob/master/src/browser.ts#L190) but I wouldn't expect that to show an error.

**Comment by arteagabriel** [comment]
Sorry I meant an error notification on the front end. I just get 'Oops, an error occurred'. The image preview box is empty but I can still hover and open in a new tab to preview. Just can't generate the image itself unless I deploy.

**Comment by styfle** [comment]
Oh right, I was wrong to include the additional change to contributing.md because the image is not actually generated in development. This version of `chrome-aws-lambda` is meant for the cloud so I intentionally made the development version emit HTML instead of the binary image in [card.ts line 14](https://github.com/styfle/og-image/blob/master/src/card.ts#L14).

I'll file an issue upstream at [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda), thanks!

**Comment by styfle** [comment]
@arteagabriel Local development has been fixed in #48 and I updated [contributing.md](https://github.com/styfle/og-image/blob/master/CONTRIBUTING.md) so I hope this works for you! 🎉

**Comment by jaredpalmer** [comment]
Sweet. Yeah I tried to do this locally last week and my spidey senses figured that a new dev command or something was in the works. Guess I was correct!

**Comment by arteagabriel** [comment]
@styfle Thanks for the quick update!

**Comment by NathanielHill** [comment]
@styfle Looks like in development mode, you just hardcode a path to the standard MacOS Chrome install... :thinking: which doesn't work for the rest of us. :cry: 

Couldn't you just conditionally use `puppeteer` instead of `puppeteer-core` for local development. :point_left: 

Looks like puppeteer will hopefully take care of installing chrome for your platform and then it would be transparent. :+1:

**Comment by NathanielHill** [comment]
Looks like it's taken care of already :pray: :+1: Can this be added?

https://github.com/alixaxel/chrome-aws-lambda/issues/7#issuecomment-450402988

@styfle

**Comment by styfle** [comment]
Hi Nathaniel,

I personally would prefer to use `puppeteer-core` along with my locally installed Chrome rather than install another version of Chrome via `puppeteer`.

However, this repo encourages forking so please feel free to use the full `puppeteer` install for your own branch or just replace the `exePath` as documented in the [CONTRIBUTING.md](https://github.com/styfle/og-image/blob/master/CONTRIBUTING.md) file.

Thanks! 👍
